language: python
matrix:
  include:
   - env: DJANGO_VERSION=1.4
     python: 2.6
   - env: DJANGO_VERSION=1.4
     python: 2.7
   - env: DJANGO_VERSION=1.8
     python: 2.7
   - env: DJANGO_VERSION=1.10
     python: 2.7
   - env: DJANGO_VERSION=1.8
     python: 3.4
   - env: DJANGO_VERSION=1.10
     python: 3.4
   - env: DJANGO_VERSION=1.8
     python: 3.5
   - env: DJANGO_VERSION=1.10
     python: 3.5
install: pip install -q Django==$DJANGO_VERSION
script: python manage.py test privateviews
