language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.10
install: pip install -q Django==$DJANGO_VERSION
script: python manage.py test privateviews
